[package]
name = "librarian"
version = "0.1.0"
edition = "2024"
description = "A librarian for a machine independent object format."
license = "Unlicense"

[dependencies]
mild = { path = "../mild" }
anyhow = "1.0"
clap = {version = "4.5", features = ["derive"]}
